# Generated by Django 5.0.8 on 2026-06-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('school_or_company', models.CharField(blank=True, max_length=150)),
                ('level', models.CharField(max_length=50)),
                ('bootcamp', models.CharField(choices=[('spring', 'Spring Boot • Angular • PostgreSQL'), ('django', 'Django • Angular • PostgreSQL'), ('flutter', 'Flutter • Django • Firebase')], max_length=30)),
                ('programming_level', models.CharField(max_length=50)),
                ('has_laptop', models.CharField(max_length=10)),
                ('motivation', models.TextField(blank=True)),
                ('discovery_source', models.CharField(blank=True, max_length=50)),
                ('preferred_contact', models.CharField(default='WhatsApp', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
